version: "3.8"
services:
  web:
    build: .
    container_name: piseiro
    ports:
      - "5000:5000"
    volumes:
      - ./src:/code/src
      - ./server.py:/code/server.py
    restart: on-failure
    depends_on:
      - mongo
  mongo:
    container_name: piseiro-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: piseiro
    volumes:
      - db_data:/data/db
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  db_data:
